### PR TITLE
build(deps): add `[gcp]` and `[parquet]` extras to enable saving Pandas dataframes to Google Storage

### PR DESCRIPTION
**Pull request by tskir**
## ✨ Context
In order to save Pandas dataframes directly into Google Storage, two optional Pandas dependencies are required: `fsspec` and `pyarrow` (for Parquet outputs).

## 🛠 What does this PR implement
Adds two new dependencies, `fsspec` and `pyarrow`.

## 🚦 Before submitting
- [x] Do these changes cover one single feature (one change at a time)?
- [x] Did you read the [contributor guideline](https://opentargets.github.io/gentropy/development/contributing/#contributing-checklist)?
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you make sure there is no commented out code in this PR?
- [x] Did you follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standards in PR title and commit messages?
- [x] Did you make sure the branch is up-to-date with the `dev` branch?
- [x] Did you write any new necessary tests?
- [x] Did you make sure the changes pass local tests (`make test`)?
- [x] Did you make sure the changes pass pre-commit rules (e.g `poetry run pre-commit run --all-files`)?

### CODE REVIEW

**Comment by d0choa** [comment]
I have no major concern here as we are already using it, but assigning to @project-defiant for review:

```
❯ poetry show fsspec
 name         : fsspec
 version      : 2023.10.0
 description  : File-system specification

required by
 - apache-airflow >=2023.10.0
 - gcsfs 2023.10.0
 - universal-pathlib >=2022.1.0
 ```

**Comment by tskir** [comment]
@d0choa Hmm. That's actually quite interesting. Even though it's marked as a dependency of apache-airflow, gcsfs and universal-pathlib, in reality it is not installed when you install Gentropy (without the change in this PR):

```
ImportError: Missing optional dependency 'fsspec'.  Use pip or conda to install fsspec.
```

**Comment by tskir** [comment]
@d0choa @project-defiant I've updated this PR to also add `pyarrow`, this is required when you want to save a Pandas df as a Parquet. Similarly, in the base version it is not installed with the rest of the package.

**Comment by project-defiant** [comment]
@tskir I think it comes to how you install the gentropy - by pip it will only use the dependencies from the https://github.com/opentargets/gentropy/blob/8ae94eae70a53ae00e5a2e795ec81e5707531109/pyproject.toml#L21, on the other hand with ` poetry install --with=dev` installs with dev dependencies that contains with the ones you look for

```{bash}
(.venv2) (base) ☁  gentropy [yt_gqs_qc_v1] ⚡  poetry show | grep -E 'pyarrow|fsspec'
fsspec                                    2023.10.0    File-system specific...
pyarrow                                   14.0.1       Python library for A...
```

**Comment by tskir** [comment]
@project-defiant Thank you for the very useful input! I totally forgot about the `package[dependency]` syntax, I'll try doing it in the way you suggested and see if it does the trick

**Review by project-defiant — APPROVED** [review]

**Pull request merged**
