### PR TITLE
chore: update ruff pre-commit and rules

### PR DESCRIPTION
**Pull request by d0choa**
## ✨ Context

Updates ruff pre-commit from 0.2.2 to 0.3.0.

After update, the next warnings and file changes were triggered

```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
  - 'ignore' -> 'lint.ignore'
  - 'select' -> 'lint.select'
  - 'flake8-quotes' -> 'lint.flake8-quotes'
  - 'pydocstyle' -> 'lint.pydocstyle'
  - 'per-file-ignores' -> 'lint.per-file-ignores'
warning: `PGH001` has been remapped to `S307`.
warning: `TRY200` has been remapped to `B904`.
warning: The following rules may cause conflicts when used with the formatter: `ISC001`. To avoid unexpected behavior, we recommend disabling these rules, either by removing them from the `select` or `extend-select` configuration, or adding them to the `ignore` configuration.
33 files reformatted, 20 files left unchanged
```

## 🛠 What does this PR implement

pre-commit.yaml update and the necessary changes in the codebase associated with the new formatting and rule changes. 

This PR addresses the above comments.

## 🚦 Before submitting

- [x] Do these changes cover one single feature (one change at a time)?
- [x] Did you read the [contributor guideline](https://opentargets.github.io/gentropy/development/contributing/#contributing-checklist)?
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you make sure there is no commented out code in this PR?
- [x] Did you follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standards in PR title and commit messages?
- [x] Did you make sure the branch is up-to-date with the `dev` branch?
- [x] Did you write any new necessary tests?
- [x] Did you make sure the changes pass local tests (`make test`)?
- [x] Did you make sure the changes pass pre-commit rules (e.g `poetry run pre-commit run --all-files`)?

### CODE REVIEW

**Comment by d0choa** [comment]
This was causing issues in #521

**Comment by d0choa** [comment]
@ireneisdoomed I added a minor refactor to one of your tests to remove a `#type: ignore` causing issues

**Comment by d0choa** [comment]
relates to #515

**Review by DSuveges — APPROVED** [review]
All pre-commit checks run successfully.

**Pull request merged**
